---
gitlab_shell_url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
gitlab_multirunner_url: https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh
download_dir: /home/ubuntu
gitlab_owner: ubuntu
